### ISSUE TITLE
README points to old page

### ISSUE THREAD

**Issue by mvz** [spree/abandoned_carts_endpoint#1]
The README points to a page for a detailed explanation, but this page no longer seems to be available.

**Comment by JDutil** [comment]
This endpoint is deprecated as we no longer provide the "Hub" service.  If you'd like to see our Wombat integrations you can view them under the wombat organization: https://github.com/wombat or review the new help center https://support.wombat.co/hc/en-us

**Comment by mvz** [comment]
Maybe then you can mention in the README that the endpoint is deprecated? I visited this project looking for a solution for abandoned carts and found I couldn't even read the documentation to see what it was about.

I have no idea what Wombat is or whether it is relevant.

**Comment by mvz** [comment]
Alternatively, you could mention in the GitHub project description that it is deprecated.
